apiVersion: v1
kind: Service
metadata:
  name: eureka-server-service
spec:
  ports:
  - port: 31002 # Inside the cluster, what port does the service expose?
    nodePort: 31002 # Which port on the node is the service available through?
    targetPort: 8761 # Which port do pods selected by this service expose?
    protocol: TCP
  selector:
    app: eureka-server
  type: NodePort
