apiVersion: v1
kind: Pod
metadata:
  name: euere-server-pod
  labels:
    app: eureka-server
spec:
  containers:
  - name: eureka-server
    image: sooseeboon/eureka_server:1
    ports:
    - name: eureka-port
      containerPort: 8761
