apiVersion: v1
kind: Service
metadata:
  name: tennis-portal-service
spec:
  ports:
  - port: 31003 # Inside the cluster, what port does the service expose?
    nodePort: 31003 # Which port on the node is the service available through?
    targetPort: 8889 # Which port do pods selected by this service expose?
    protocol: TCP
  selector:
    app: tennis-portal-service
  type: NodePort
