apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  ports:
  - port: 31004 # Inside the cluster, what port does the service expose?
    nodePort: 31004 # Which port on the node is the service available through?
    targetPort: 3306 # Which port do pods selected by this service expose?
    protocol: TCP
  selector:
    app: mysql
  type: NodePort
