apiVersion: v1
kind: Service
metadata:
  name: player-service
spec:
  ports:
  - port: 31006 # Inside the cluster, what port does the service expose?
    nodePort: 31006 # Which port on the node is the service available through?
    targetPort: 8883 # Which port do pods selected by this service expose?
    protocol: TCP
  selector:
    app: player-service
  type: NodePort
