apiVersion: apps/v1
kind: Deployment
metadata:
  name: player-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: player-service
  template:
    metadata:
      labels:
        app: player-service
    spec:
      containers:
      - name: player-service
        image: sooseeboon/player_service:1
        ports:
        - name: player-port
          containerPort: 8883
        env:
        - name: spring.datasource.url
          value: "jdbc:mysql://mysql-service:31004/Tennis?createDatabaseIfNotExist=true&useSSL=true"
        - name: eureka.client.service-url.defaultZone
          value: "http://eureka-server-service:31002/eureka/"
        - name: spring.cloud.config.uri
          value: "http://config-server-service:31001"


