apiVersion: apps/v1
kind: Deployment
metadata:
  name: lesson-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lesson-service
  template:
    metadata:
      labels:
        app: lesson-service
    spec:
      containers:
      - name: lesson-service
        image: sooseeboon/lesson_service:5
        ports:
        - name: lesson-port
          containerPort: 8883
        env:
        - name: spring.datasource.url
          value: "jdbc:mysql://mysql-service:31004/Tennis?createDatabaseIfNotExist=true&useSSL=true"
        - name: eureka.client.service-url.defaultZone
          value: "http://eureka-server-service:31002/eureka/"
        - name: spring.cloud.config.uri
          value: "http://config-server-service:31001"


