apiVersion: v1
kind: Service
metadata:
  name: lesson-service
spec:
  ports:
  - port: 31008 # Inside the cluster, what port does the service expose?
    nodePort: 31008 # Which port on the node is the service available through?
    targetPort: 8890 # Which port do pods selected by this service expose?
    protocol: TCP
  selector:
    app: lesson-service
  type: NodePort
