apiVersion: v1
kind: Pod
metadata:
  name: config-server-pod
  labels:
    app: config-server
spec:
  containers:
  - name: config-server
    image: sooseeboon/config_server:1
    ports:
    - name: config-port
      containerPort: 8887
