apiVersion: v1
kind: Service
metadata:
  name: config-server-service
spec:
  ports:
  - port: 31001 # Inside the cluster, what port does the service expose?
    nodePort: 31001 # Which port on the node is the service available through?
    targetPort: 8887 # Which port do pods selected by this service expose?
    protocol: TCP
  selector:
    app: config-server
  type: NodePort
